### ISSUE TITLE
how to use,could you you give more description

### ISSUE THREAD

**Issue by kintong3000** [fuergaosi233/chatgpt-proxy-server#3]
could you you give more description

**Comment by kintong3000** [comment]
How to modify config？

**Comment by fuergaosi233** [comment]
It needs to provide the environment variable to do the forwarding

**Comment by kintong3000** [comment]
CHATGPT_URL 填什么

**Comment by kintong3000** [comment]
> It needs to provide the environment variable to do the forwarding


你好，CHATGPT_URL 该填什么

**Comment by kintong3000** [comment]
是不是启动了这个服务就是相当于一个reverse proxy URL，像
<img width="833" alt="image" src="https://user-images.githubusercontent.com/85821314/222901072-7a78581b-ad13-4bcd-aa50-7c2669d8eaba.png">这个一样吗
不是很懂

**Comment by fuergaosi233** [comment]
> 是不是启动了这个服务就是相当于一个reverse proxy URL，像 <img alt="image" width="833" src="https://user-images.githubusercontent.com/85821314/222901072-7a78581b-ad13-4bcd-aa50-7c2669d8eaba.png">这个一样吗 不是很懂

是的

**Comment by kintong3000** [comment]
> > It needs to provide the environment variable to do the forwarding
> 
> 你好，CHATGPT_URL 该填什么

我尝试填chat.openai.com/chat
我也设置了代理，并且能够上chatGPT，但是启动服务后提示TCP timeout，是我CHATGPT_URL没填对吗

**Comment by kintong3000** [comment]
我想是要填一个endpoint？（我也不知道是不是这么叫），而这个是隐藏的不能公开的
